run:
  deadline: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - unused
    - gosimple
    - typecheck
    - govet
    - staticcheck
    - ineffassign
    - stylecheck
    - unconvert
    - goconst
    - gci
    - scopelint
    - gocritic
