name: Build and test Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Check out source code
        uses: actions/checkout@v1
      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: |
          cd cmd/myaction
          go build .
      - name: Test
        env:
          GOPROXY: "https://proxy.golang.org"
        run: |
          docker run --name mypg -p 5432:5432 -v `pwd`/main.go:/var/lib/main.go -e POSTGRES_PASSWORD=secret -d postgres
          go test -v ./...